start cmd.exe /k "java -jar  microservices/authserver/build/libs/microservices/authserver-0.0.1-SNAPSHOT.jar"
start cmd.exe /k "java -jar  microservices/discovery/build/libs/microservices/discovery-0.0.1-SNAPSHOT.jar"
start cmd.exe /k "java -jar  microservices/edge/build/libs/microservices/edge-0.0.1-SNAPSHOT.jar"
start cmd.exe /k "java -jar  microservices/frontend/build/libs/microservices/frontend-0.0.1-SNAPSHOT.jar"
REM start cmd.exe /k "java -jar  microservices/turbine/build/libs/microservices/turbine-0.0.1-SNAPSHOT.jar"
REM start cmd.exe /k "java -jar  microservices/hystrixdashboard/build/libs/microservices/hystrixdashboard-0.0.1-SNAPSHOT.jar"
